/**
 * PrisNames — Registrar Error Codes
 *
 * Business-layer error codes for registrar orchestration.
 * Separate from ProviderErrorCode (which is provider-adapter level).
 */

export const REGISTRAR_ERROR_CODES = {
  INVALID_FQDN: 'REGISTRAR_INVALID_FQDN',
  IDN_NOT_SUPPORTED: 'REGISTRAR_IDN_NOT_SUPPORTED',
  FQDN_ALREADY_ACTIVE: 'REGISTRAR_FQDN_ALREADY_ACTIVE',
  OPERATION_NOT_FOUND: 'REGISTRAR_OPERATION_NOT_FOUND',
  INVALID_STATE_TRANSITION: 'REGISTRAR_INVALID_STATE_TRANSITION',
  UNSAFE_RETRY: 'REGISTRAR_UNSAFE_RETRY',
  UNSAFE_ACTION: 'REGISTRAR_UNSAFE_ACTION',
  VERIFICATION_FAILED: 'REGISTRAR_VERIFICATION_FAILED',
  DOMAIN_NOT_FOUND: 'REGISTRAR_DOMAIN_NOT_FOUND',
  ORDER_NOT_FOUND: 'REGISTRAR_ORDER_NOT_FOUND',
  CAPABILITY_UNAVAILABLE: 'REGISTRAR_CAPABILITY_UNAVAILABLE',
  STALE_CLAIM: 'REGISTRAR_STALE_CLAIM',
} as const;

export type RegistrarErrorCode = (typeof REGISTRAR_ERROR_CODES)[keyof typeof REGISTRAR_ERROR_CODES];
