import { describe, it, expect } from 'vitest';
import { generateOtp, hashOtp, verifyOtp } from '../otp.js';

const TEST_PEPPER = 'test-pepper-for-unit-tests-minimum-32-chars-long';

describe('otp', () => {
  it('should generate a 6-digit string', () => {
    for (let i = 0; i < 100; i++) {
      const otp = generateOtp();
      expect(otp).toMatch(/^\d{6}$/);
      const num = parseInt(otp, 10);
      expect(num).toBeGreaterThanOrEqual(100000);
      expect(num).toBeLessThanOrEqual(999999);
    }
  });

  it('should generate different OTPs (not constant)', () => {
    const otps = new Set<string>();
    for (let i = 0; i < 50; i++) {
      otps.add(generateOtp());
    }
    // With 50 random 6-digit codes, we'd expect most to be unique
    expect(otps.size).toBeGreaterThan(40);
  });

  it('should hash OTP with HMAC-SHA256 producing a 64-char hex string', () => {
    const hash = hashOtp('123456', TEST_PEPPER);
    expect(hash).toMatch(/^[0-9a-f]{64}$/);
  });

  it('should produce different hashes with different peppers', () => {
    const hash1 = hashOtp('123456', TEST_PEPPER);
    const hash2 = hashOtp('123456', 'different-pepper-also-32-chars-long-xxxx');
    expect(hash1).not.toBe(hash2);
  });

  it('should verify a correct OTP', () => {
    const otp = '654321';
    const hash = hashOtp(otp, TEST_PEPPER);
    expect(verifyOtp(otp, hash, TEST_PEPPER)).toBe(true);
  });

  it('should reject an incorrect OTP', () => {
    const hash = hashOtp('654321', TEST_PEPPER);
    expect(verifyOtp('123456', hash, TEST_PEPPER)).toBe(false);
  });

  it('should reject verification with wrong pepper', () => {
    const otp = '111222';
    const hash = hashOtp(otp, TEST_PEPPER);
    expect(verifyOtp(otp, hash, 'wrong-pepper-also-32-chars-long-xxxxx')).toBe(false);
  });

  it('should use constant-time comparison', () => {
    // Structural test: verifyOtp uses timingSafeEqual internally
    // We verify that it still returns correct results for edge cases
    const otp = '000000'; // Edge: all zeros (not generated by randomInt, but valid input)
    const hash = hashOtp(otp, TEST_PEPPER);
    expect(verifyOtp(otp, hash, TEST_PEPPER)).toBe(true);
    expect(verifyOtp('000001', hash, TEST_PEPPER)).toBe(false);
  });
});
